# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0005_auto_20181018_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
    ]
