# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0007_auto_20181018_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hood',
            old_name='admin',
            new_name='user',
        ),
    ]
