# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtaa', '0009_auto_20181019_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
